[versions]
agp = "8.13.0"

[libraries]

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
maven-publish = { id = 'maven-publish' }
java-library = { id = 'java-library' }
